# Generated by Django 4.2.3 on 2024-10-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Наименование')),
                ('brand', models.CharField(choices=[('AS', 'Asus'), ('AP', 'Apple'), ('HP', 'Hewlett-Packard'), ('DL', 'Dell')], default='DL', max_length=2, verbose_name='Бренд')),
                ('year_of_release', models.IntegerField(default=2020, verbose_name='Год выпуска')),
                ('ram', models.IntegerField(default=8, verbose_name='Оперативная память (Гб)')),
                ('hdd', models.IntegerField(default=120, verbose_name='Объем жесткого диска (Гб)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('balance', models.IntegerField(blank=True, default=0, verbose_name='Остаток')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
