# Generated by Django 4.2.3 on 2024-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_notebook_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('status', models.CharField(choices=[('NP', 'Не опубликован'), ('OP', 'Опубликован'), ('ZB', 'Забанен')], default='NP', max_length=2, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('C1', 'Категория 1'), ('C2', 'Категория 2'), ('C3', 'Категория 3')], default='NP', max_length=2, verbose_name='Категория')),
            ],
        ),
    ]
