# Generated by Django 4.2.3 on 2024-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_post_category_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='post',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
