# Generated by Django 4.2.3 on 2024-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_notebook_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
